apiVersion: v1
kind: Service
metadata:
  name: logistics-api-svc
  namespace: ecommerce
spec:
  selector:
    app: logistics-api
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
