-- V1__init_inventory_schema.sql
-- Inventory Service schema (PostgreSQL)

-- =========================================================
-- 1) inventory_stock (SKU 단위 재고)
--   - total_quantity: 전체 재고
--   - reserved_quantity: 예약(점유) 재고
--   - version: 낙관적 락용(옵션)
-- =========================================================
CREATE TABLE IF NOT EXISTS inventory_stock (
    sku               VARCHAR(64) PRIMARY KEY,
    total_quantity    BIGINT      NOT NULL DEFAULT 0,
    reserved_quantity BIGINT      NOT NULL DEFAULT 0,
    version           BIGINT      NOT NULL DEFAULT 0,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_stock_total_nonneg CHECK (total_quantity >= 0),
    CONSTRAINT chk_stock_reserved_nonneg CHECK (reserved_quantity >= 0),
    CONSTRAINT chk_stock_reserved_le_total CHECK (reserved_quantity <= total_quantity)
    );

-- =========================================================
-- 2) inventory_reservation (예약 헤더)
--   - order_id: order 서비스의 주문 ID(외부 참조, FK 불가)
--   - status: RESERVED/CONFIRMED/CANCELED/EXPIRED
--   - expires_at: TTL 만료 시각
-- =========================================================
CREATE TABLE IF NOT EXISTS inventory_reservation (
    id         UUID        PRIMARY KEY,
    order_id   BIGINT      NOT NULL UNIQUE,
    status     VARCHAR(16) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS idx_inventory_reservation_expire_target
    ON inventory_reservation (status, expires_at);

-- =========================================================
-- 3) inventory_reservation_item (예약 상세)
--   - 한 예약에 여러 SKU
-- =========================================================
CREATE TABLE IF NOT EXISTS inventory_reservation_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id UUID        NOT NULL,
    sku            VARCHAR(64) NOT NULL,
    quantity       BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_reservation_item_reservation
    FOREIGN KEY (reservation_id) REFERENCES inventory_reservation(id) ON DELETE CASCADE
    );
CREATE INDEX IF NOT EXISTS idx_reservation_item_sku
    ON inventory_reservation_item (sku);

CREATE UNIQUE INDEX IF NOT EXISTS uq_reservation_item_reservation_sku
    ON inventory_reservation_item (reservation_id, sku);