CREATE TABLE IF NOT EXISTS outbox_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id   VARCHAR(64) NOT NULL,
    event_type     VARCHAR(128) NOT NULL,
    payload        JSONB NOT NULL,
    status         VARCHAR(16) NOT NULL DEFAULT 'PENDING', -- PENDING, SENT, FAILED
    retry_count    INT NOT NULL DEFAULT 0,
    next_retry_at  TIMESTAMPTZ NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at        TIMESTAMPTZ NULL
    );

CREATE INDEX IF NOT EXISTS idx_outbox_pending
    ON outbox_event(status, created_at);

CREATE INDEX IF NOT EXISTS idx_outbox_next_retry
    ON outbox_event(status, next_retry_at);
