-- =========================================================
-- 1) orders
-- =========================================================
CREATE TABLE IF NOT EXISTS orders (
                                      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      order_no         VARCHAR(32)  NOT NULL UNIQUE,
    user_id          BIGINT       NOT NULL,
    status           VARCHAR(32)  NOT NULL,  -- CREATED, RESERVED, PAID, COMPLETED, FAILED, CANCELED, EXPIRED...
    total_amount     DECIMAL(19, 2)NOT NULL DEFAULT 0,
    discount_amount  DECIMAL(19, 2)NOT NULL DEFAULT 0,
    pay_amount       DECIMAL(19, 2)NOT NULL DEFAULT 0,
    failure_reason   TEXT         NULL,
    saga_id          UUID         NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_orders_amounts_nonneg CHECK (
                                                   total_amount >= 0 AND discount_amount >= 0 AND pay_amount >= 0
                                               )
    );

-- =========================================================
-- 2) order_item (snapshot)
-- =========================================================
CREATE TABLE IF NOT EXISTS order_item (
                                          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          order_id                BIGINT       NOT NULL,
                                          sku                     VARCHAR(64)  NOT NULL,
    quantity                INTEGER      NOT NULL,
    price_snapshot          DECIMAL(19, 2)NOT NULL,
    variant_name_snapshot   VARCHAR(255) NULL,
    product_name_snapshot   VARCHAR(255) NULL,
    option_json_snapshot    JSONB        NULL,
    category_path_snapshot  VARCHAR(512) NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_item_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_order_item_order_id
    ON order_item(order_id);


-- =========================================================
-- 3) order_saga_state
-- =========================================================
CREATE TABLE IF NOT EXISTS order_saga_state (
                                                saga_id      UUID        PRIMARY KEY,
                                                order_id     BIGINT      NOT NULL UNIQUE,
                                                state        VARCHAR(32) NOT NULL,  -- STARTED, INVENTORY_RESERVED, RESERVE_DONE, COMPENSATING, SUCCEEDED, FAILED ...
    last_error   TEXT        NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_saga_state_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_saga_state_state_updated
    ON order_saga_state (state, updated_at DESC);

-- =========================================================
-- 4) idempotency_request (API 요청 멱등성)
-- =========================================================
CREATE TABLE IF NOT EXISTS idempotency_request (
                                                   idem_key      VARCHAR(128) PRIMARY KEY, -- Idempotency-Key 헤더 값
    request_hash  CHAR(64)     NOT NULL,
    order_id      BIGINT       NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'IN_PROGRESS', -- IN_PROGRESS, COMPLETED, FAILED
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_idem_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
    );

CREATE INDEX IF NOT EXISTS idx_idem_order_id
    ON idempotency_request (order_id);

CREATE INDEX IF NOT EXISTS idx_idem_status_created
    ON idempotency_request (status, created_at DESC);