-- V1__init_product_schema.sql
-- Product Service schema (PostgreSQL)

-- =========================
-- category
-- =========================

CREATE TABLE IF NOT EXISTS category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    parent_id   BIGINT      NULL,
    sort_order  INT         NOT NULL DEFAULT 0,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', --ACTIVE, INACTIVE
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS idx_category_parent_sort
    ON category(parent_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_category_status
    ON category(status);

-- =========================
-- product
-- =========================
CREATE TABLE IF NOT EXISTS product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    brand_name  VARCHAR(120) NOT NULL,
    category_id BIGINT NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    description TEXT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS idx_product_category_status
    ON product(category_id, status);

CREATE INDEX IF NOT EXISTS idx_product_status_created_at
    ON product(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_product_brand_status
    ON product(brand_name, status);

-- =========================
-- product_variant (SKU)
-- =========================
CREATE TABLE IF NOT EXISTS product_variant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    sku         VARCHAR(80) NOT NULL ,
    price       DECIMAL(19, 2) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    option_json jsonb NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS idx_variant_product
    ON product_variant(product_id);

-- =========================
-- product_image
-- =========================
CREATE TABLE IF NOT EXISTS product_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT NOT NULL,
    storage_key  VARCHAR(500) NOT NULL,
    url          VARCHAR(1000) NOT NULL,
    type         VARCHAR(20) NOT NULL DEFAULT 'DETAIL', -- THUMBNAIL, DETAIL
    sort_order   INT NOT NULL DEFAULT 0,
    is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS idx_product_image_product_sort
    ON product_image(product_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_product_image_product_primary
    ON product_image(product_id, is_primary);
