apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: sparta-msa-final-project-inventory-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: db-secret
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://inventory-db:5432/inventorydb"
              #value: "jdbc:postgresql://localhost:5434/inventorydb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.ecommerce.svc.cluster.local:9092"