apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-api
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-api
  template:
    metadata:
      labels:
        app: address-api
    spec:
      containers:
        - name: address-api
          image: sparta-msa-final-project-address-api:real
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: db-secret
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://address-db:5432/addressdb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
