input {
  file {
    path => "/usr/share/logstash/logs/user-activity.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "user-activity"
  }

  file {
    path => "/usr/share/logstash/logs/orders.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "orders"
  }

  file {
    path => "/usr/share/logstash/logs/search-keyword.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "search-keyword"
  }
}

filter {
  date {
    match => ["timestamp", "ISO8601"]
    target => "timestamp"
  }
}

output {
  if [type] == "user-activity" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "ecommerce-logs-user-activity"
    }
  } else if [type] == "orders" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "ecommerce-logs-orders"
    }
  } else if [type] == "search-keyword" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "ecommerce-logs-search-keyword"
    }
  }

  stdout { codec => rubydebug }
}