server:
  port: 8081

spring:
  application:
    name: product-api

  datasource:
    #url: jdbc:postgresql://product-db:5433/productdb
    url: jdbc:postgresql://localhost:5433/productdb
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kafka:
    #bootstrap-servers: kafka:29092  # ??? ??? ??
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer   # ??? key? String -> bytes? ???
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? value? String -> bytes? ???
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retry.backoff.ms: 1000
        max.block.ms: 90000

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    aws:
      s3:
        endpoint: http://localhost:9000
        path-style-access-enabled: true
        bucket: product-images
      region:
        static: us-east-1
      credentials:
        access-key: admin
        secret-key: password

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.example: DEBUG
#    org.apache.kafka: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG
    org.springframework.transaction: DEBUG
