CREATE TABLE IF NOT EXISTS shipment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT       NOT NULL UNIQUE,
    tracking_number  VARCHAR(64),
    status           VARCHAR(16)  NOT NULL DEFAULT 'READY',
    carrier          VARCHAR(64),
    recipient_name   VARCHAR(128),
    recipient_address VARCHAR(512),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shipment_order_id ON shipment (order_id);
CREATE INDEX IF NOT EXISTS idx_shipment_status   ON shipment (status);
