CREATE TABLE IF NOT EXISTS shipment_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT       NOT NULL,
    status      VARCHAR(16)  NOT NULL,
    description VARCHAR(512),
    event_id    VARCHAR(128),
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_history_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id)
);

CREATE INDEX IF NOT EXISTS idx_history_shipment_id ON shipment_status_history (shipment_id);
