CREATE TABLE IF NOT EXISTS shipment_address_history (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id                BIGINT        NOT NULL,
    previous_recipient_name    VARCHAR(128),
    previous_recipient_address VARCHAR(512),
    new_recipient_name         VARCHAR(128),
    new_recipient_address      VARCHAR(512),
    changed_at                 TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_addr_history_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id)
);

CREATE INDEX IF NOT EXISTS idx_addr_history_shipment_id ON shipment_address_history (shipment_id);
