apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: product-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: db-secret
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://product-db:5432/productdb"
              #value: "jdbc:postgresql://localhost:5433/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"