server:
  port: 8082

spring:
  application:
    name: inventory-api

  datasource:
    #url: jdbc:postgresql://inventory-db:5434/inventorydb
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kafka:
    #bootstrap-servers: kafka:29092  # ??? ??? ??
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer   # ??? key? String -> bytes? ???
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? value? String -> bytes? ???
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retry.backoff.ms: 1000
        max.block.ms: 90000

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.example: DEBUG
    #    org.apache.kafka: DEBUG
    org.apache.kafka: INFO
    #org.springframework.kafka: DEBUG
    org.springframework.kafka: INFO
    #org.springframework.transaction: DEBUG
    org.springframework.transaction: INFO